name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check variables
      env:
        EVENT_NAME: ${{ github.event_name }}
        REPO_NAME: ${{ github.event.repository.name }}
        REPO_BRANCH: ${{ github.head_ref }}
      run: echo "event name $EVENT_NAME head_branch $REPO_BRANCH"
    - name: Check image name
      env:
        REPO_NAME: ${{ github.event.repository.name }}
        REPO_BRANCH: ${{ github.head_ref }}
      run: echo "docker image name would be $REPO_NAME:$REPO_BRANCH"
      if: github.event_name == 'pull_request' 
    - name: Build the Docker image
      env:
        REPO_NAME: ${{ github.event.repository.name }}
        REPO_BRANCH: ${{ github.head_ref }}
      run: docker build . --file Dockerfile --tag $REPO_NAME:$REPO_BRANCH
      if: github.event_name == 'pull_request' 
