name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Extract branch name
      shell: bash
      run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
    - name: Test
      run: echo "${BRANCH_NAME}"
    - name: Check image name
      env:
        REPO_NAME: ${{ github.event.repository.name }}
        REPO_BRANCH: ${{ github.ref }}
      run: echo "docker image name would be $REPO_NAME:$REPO_BRANCH"
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
