name: push on master

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check variables
        env:
          EVENT_NAME: ${{ github.event_name }}
          REPO_NAME: ${{ github.event.repository.name }}
          REPO_HEAD_REF: ${{ github.head_ref }}
          REPO_REF: ${{ github.ref}}
        run: echo "event name $EVENT_NAME head_branch $REPO_HEAD_REF $REPO_REF"

      - name: Check image name (Push on Master)
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: echo "docker image name would be $REPO_NAME:latest"

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build the Docker image (Push on master)
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: docker build . --file Dockerfile --tag eurobenchtest/$REPO_NAME:latest

      - name: Get the docker image testing material
        run: wget -O test_docker_call.py https://raw.githubusercontent.com/eurobench/docker_test/master/test_docker_call.py

      - name: test the Docker image
        env:
          DOCKER_IMAGE: eurobenchtest/${{ github.event.repository.name }}:latest
          TEST_PLAN: tests/test_plan.xml
        run: python3 test_docker_call.py

      - name: Push to Docker hub (Push on master)
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: docker push eurobenchtest/$REPO_NAME:latest
